export const projects = [
  {
    title: "Firstrade Portfolio Analysis",
    year: "2024",
    course: "Side",
    category: "ML / Data Ana.",
    description:
      "This suite of Python scripts and Jupyter notebook reconstructs a complete Firstrade portfolio transaction history from CSV data. It enables precise tracking of portfolio evolution, detailed performance analysis over any time period, and accurate return calculations that account for dividends, reinvestments, and corporate actions like stock splits.",
    tech_stack: "Python, Pandas, Matplotlib, Seaborn",
    githubUrl: "https://github.com/Jason-Wuuuu/Firstrade-Portfolio-Analyzer",
    demoUrl: "",
    screenshots: ["firstrade/output1.png", "firstrade/output2.png"],
  },
  {
    title: "Tripper",
    year: "2024",
    course: "Side",
    category: "Web Dev",
    description:
      "A dynamic, user-friendly web app designed to transform the way travelers plan and experience trips.",
    tech_stack: "Java, TypeScript, Spring Boot, Next.js, MongoDB",
    githubUrl: "https://github.com/Jason-Wuuuu/Tripper",
    demoUrl: "",
    screenshots: ["tripper/trips.png", "tripper/trips_2.png"],
  },
  {
    title: "Bank Ledger System",
    year: "2024",
    course: "Interview 2nd Round",
    category: "Web Dev",
    description:
      "Developed a bank ledger system implementing the Event Sourcing pattern to maintain an immutable transaction history, ensuring auditability and reconstruction of account balances.",
    tech_stack: "Java, Spring Boot",
    githubUrl: "https://github.com/Jason-Wuuuu/Bank-Ledger-System",
    demoUrl: "",
    screenshots: [],
  },
  {
    title: "Seq2Seq Translation Model",
    year: "2024",
    course: "NLP Course",
    category: "ML / Data Ana.",
    description:
      "A seq2seq model to translate French text into English using the iwslt2017 dataset, processing over 50,000 sentence pairs.",
    tech_stack: "Python, TensorFlow",
    githubUrl: "",
    demoUrl: "",
    screenshots: [
      "seq2seq/model.png",
      "seq2seq/translation_1.png",
      "seq2seq/translation_2.png",
    ],
  },
  {
    title: "Stock Price Forecast",
    year: "2024",
    course: "Side",
    category: "ML / Data Ana.",
    description:
      "A LSTM model designed to forecast stock prices based on historical data, trained using a variety of features and technical indicators. It achieves an average R^2 score of 0.96 and an average Mean Absolute Percentage Error of 0.1%.",
    tech_stack: "Python, TensorFlow, scikit-learn, pandas",
    githubUrl: "https://github.com/Jason-Wuuuu/stock_price_prediction",
    demoUrl: "",
    screenshots: [
      "stock_price_lstm/TSLA.png",
      "stock_price_lstm/NVDA.png",
      "stock_price_lstm/AAPL.png",
      "stock_price_lstm/PLTR.png",
    ],
  },
  {
    title: "Visual Board",
    year: "2024",
    course: "Side",
    category: "Web Dev",
    description:
      "An interactive stock dashboard featuring historical data charts, market recommendations, and stock analysis.",
    tech_stack: "JavaScript, Python, React, FastAPI, Redis",
    githubUrl: "https://github.com/Jason-Wuuuu/VisualBoard",
    demoUrl: "https://youtu.be/hOSht_Mvv34",
    screenshots: ["visual_board/stock1.png", "visual_board/stock2.png"],
  },
  {
    title: "IMDB Movie Review Analysis (Word2Vec)",
    year: "2024",
    course: "NLP Course",
    category: "ML / Data Ana.",
    description:
      "A Word2Vec Skip-Gram model developed with TensorFlow to analyze and generate word embeddings from the IMDB movie review dataset, enhancing understanding of semantic word relationships.",
    tech_stack: "Python, TensorFlow, NLTK",
    githubUrl: "",
    demoUrl: "",
    screenshots: ["word2vec/word_vec.png"],
  },
  {
    title: "Author Classification (MLP)",
    year: "2024",
    course: "NLP Course",
    category: "ML / Data Ana.",
    description:
      "A Multi-Layer Perceptron (MLP) model, fully coded from scratch in Python, to classify sentences by their corresponding authors. It employs tokenization and TF-IDF vectorization with optimization, regularization, and cross-validation.",
    tech_stack: "Python, TensorFlow, NLTK, scikit-learn",
    githubUrl: "",
    demoUrl: "",
    screenshots: ["mlp/score.png"],
  },
  {
    title: "Stevens Marketplace",
    year: "2023",
    course: "Web Programming Course Group",
    category: "Web Dev",
    description:
      "A community-centric platform that facilitates the discovery and management of pre-owned items, featuring seamless and secure real-time messaging.",
    tech_stack: "JavaScript, React, GraphQL, MongoDB, Firebase, Redux, Redis",
    githubUrl: "https://github.com/Jason-Wuuuu/CS554-GroupVVIV",
    demoUrl: "",
    screenshots: [
      "stevens_marketplace/demo.gif",
      "stevens_marketplace/chat.gif",
    ],
  },
  {
    title: "Event Master",
    year: "2023",
    course: "Agile Methods Course Group",
    category: "Web Dev",
    description:
      "A full-stack web app that utilizes Eventbrite & Ticketmaster APIs for seamless event discovery, interactive voting, and personalized schedule planning. It implements web scraping to compensate for missing functionality in Eventbrite's API.",
    tech_stack: "JavaScript, Python, React, Node.js, Express.js, MongoDB",
    githubUrl: "https://github.com/Jason-Wuuuu/CS555A-Team19-Project",
    demoUrl: "",
    screenshots: [
      "event_master/home.png",
      "event_master/profile.png",
      "event_master/eventlist.png",
      "event_master/eventdetail.png",
      "event_master/eventpoll.png",
    ],
  },
  {
    title: "Marvel Comic App",
    year: "2023",
    course: "Web Programming Course",
    category: "Web Dev",
    description:
      "A full-stack web application that integrates the Marvel API for comic discovery and collection.",
    tech_stack: "JavaScript, React, Node.js, GraphQL, Redis, Redux",
    githubUrl: "https://github.com/Jason-Wuuuu/Marvel-Comic-Web-App",
    demoUrl: "https://www.youtube.com/watch?v=rKfUaeMGa3w",
    screenshots: [
      "marvel_app/home.png",
      "marvel_app/list.png",
      "marvel_app/detail.png",
      "marvel_app/collection.png",
    ],
  },
  {
    title: "Support Vector Machine",
    year: "2022",
    course: "ML Course",
    category: "ML / Data Ana.",
    description:
      "Coursework that involves deriving the hyperplane equation from given data points and Lagrange multipliers, calculating distances to the hyperplane, and classifying new points.",
    tech_stack: "Python, NumPy, pandas",
    githubUrl: "",
    demoUrl: "",
    screenshots: ["svm/hyperplane.png"],
  },
  {
    title: "Breast Cancer Detection",
    year: "2022",
    course: "ML Course",
    category: "ML / Data Ana.",
    description:
      "Coursework that includes implementing logistic regression from scratch for breast cancer diagnosis, with a focus on Stochastic and Mini-Batch Gradient Descent optimizations, and model performance evaluation through precision, recall, and accuracy metrics.",
    tech_stack: "Python, NumPy, pandas",
    githubUrl: "",
    demoUrl: "",
    screenshots: [],
  },
  {
    title: "Diabetes Detection (PCA)",
    year: "2022",
    course: "ML Course",
    category: "ML / Data Ana.",
    description:
      "Coursework that involves dimensionality reduction on a diabetes dataset using Principal Component Analysis (PCA), implemented with Python's sklearn library. PCA was applied to reduce the feature space from eight dimensions to two.",
    tech_stack: "Python, scikit-learn, pandas",
    githubUrl: "",
    demoUrl: "",
    screenshots: ["pca/principal_components.png"],
  },
  {
    title: "Image Compression (SVD)",
    year: "2022",
    course: "ML Course",
    category: "ML / Data Ana.",
    description:
      "Coursework that involves the practical application of Singular Value Decomposition (SVD) to compress images. SVD was used to decompose and reconstruct images at varying levels of compression.",
    tech_stack: "Python, NumPy",
    githubUrl: "",
    demoUrl: "",
    screenshots: ["svd/image_compression.png"],
  },
  {
    title: "Memory Maker",
    year: "2019",
    course: "Undergrad Senior",
    category: "Mobile Dev",
    description:
      "An iOS app for suggesting compositions in mobile photography and for virtual postcard sharing. It achieved 2nd place in the competition for the International ICT Innovative Services Awards.",
    tech_stack: "Swift, Python, TensorFlow, Firebase",
    githubUrl: "",
    demoUrl: "",
    screenshots: ["memory_maker/demo.gif"],
  },
];
